input_number:
  setpoint:
    name: Setpoint
    min:  20
    max:  350
    step: 1
    mode: box
    unit_of_measurement: "°C"
    icon: mdi:target
  p0h: &alarm
    name: Probe0 Hi
    min: -400
    max: 400
    step: 1
    mode: box
    unit_of_measurement: "°C"
    icon: mdi:target
  p0l:
    <<: *alarm
    name: Probe0 Lo
  p1h:
    <<: *alarm
    name: Probe1 Hi
  p1l:
    <<: *alarm
    name: Probe1 Lo
  p2h:
    <<: *alarm
    name: Probe2 Hi
  p2l:
    <<: *alarm
    name: Probe2 Lo
  p3h:
    <<: *alarm
    name: Probe3 Hi
  p3l:
    <<: *alarm
    name: Probe3 Lo

input_text:
  api_key:
    name: Heatermeter API Key
    icon: mdi:key
  host:
    name: Heatermeter Host
    icon: mdi:uri
