input_number:
  setpoint:
    name: Setpoint
    initial: 180
    min:  20
    max:  350
    step: 1
    mode: box
    unit_of_measurement: "°C"
    icon: mdi:target
  p0h:
    name: Probe0 Hi
    initial: 75
    min: -0
    max: 400
    step: 1
    mode: box
    unit_of_measurement: "°C"
    icon: mdi:target
  p0l:
    name: Probe0 Lo
    initial: 10
    min: -0
    max: 400
    step: 1
    mode: box
    unit_of_measurement: "°C"
    icon: mdi:target
  p1h:
    name: Probe1 Hi
    initial: 75
    min: -0
    max: 400
    step: 1
    mode: box
    unit_of_measurement: "°C"
    icon: mdi:target
  p1l:
    name: Probe1 Lo
    initial: 10
    min: -0
    max: 400
    step: 1
    mode: box
    unit_of_measurement: "°C"
    icon: mdi:target
  p2h:
    name: Probe2 Hi
    initial: 75
    min: -0
    max: 400
    step: 1
    mode: box
    unit_of_measurement: "°C"
    icon: mdi:target
  p2l:
    name: Probe2 Lo
    initial: 10
    min: -0
    max: 400
    step: 1
    mode: box
    unit_of_measurement: "°C"
    icon: mdi:target
  p3h:
    name: Probe3 Hi
    initial: 75
    min: -0
    max: 400
    step: 1
    mode: box
    unit_of_measurement: "°C"
    icon: mdi:target
  p3l:
    name: Probe3 Lo
    initial: 10
    min: -0
    max: 400
    step: 1
    mode: box
    unit_of_measurement: "°C"
    icon: mdi:target

input_text:
  api_key:
    name: Heatermeter API Key
    initial: 111111111111
    icon: mdi:key
  host:
    name: Heatermeter Host
    initial: heatermeter.local
    icon: mdi:uri
